### ISSUE TITLE
Semantic Domain - 3 things

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#100]
- [x] 1. Semantic domain data below the list rather than beside it
- [x] 2. Position in semantic domain list should not be remembered between dictionaries
- [x] 3. A mix of languages is showing is the semantic domain list

1) At first I thought it was not showing Sem Dom data.  Later I discovered that maybe it is showing, but it is so far down the screen that I didn’t see it at first--apparently I needed to scroll.  It looks like the beginning of the entries is starting just below the list of semantic domains.   (Verna didn’t see this in Chrome--for her, the first entry started at the same vertical place on the page as the beginning of the SemDom list.)  Images:  SemDomShowingInDictionary.png, SemDomsNotVisibleWithoutScrolling.png  (I am using Firefox 77.0.1.)
<img width="634" alt="SemDomsNotVisibleWithoutScrolling" src="https://user-images.githubusercontent.com/53490028/85879206-8e1a6900-b79f-11ea-9c0c-a77c5e9b089b.PNG">
 Beth

2) When I click on the Semantic Domain tab in one dictionary, it remembers the expanding/collapsing of the last time/dictionary I clicked on the Semantic Domain tab. This is true for Webonary 1.0 as well.

![SemanticDomains](https://user-images.githubusercontent.com/53490028/85879025-4267bf80-b79f-11ea-823b-fab7b8d8b80d.JPG)

**Comment by bbryson** [comment]
These screenshots are from:

https://www.webonary.work/ut-hun/browse/categories/

The backup for this database is: Dukkawa 2020-06-26 1107 Jun26testing.fwbackup

It is in the folder with all the backups for testing Webonary:  [FLEx backups for testing](https://drive.google.com/drive/folders/1IDVEimJF05igvPLuShvguYeYY1fTzJEf?usp=sharing)

As seen in the entries showing at the bottom of the image, the entries aw and ba have domains 6.7 and 6.2, so it is correct that they would show when domain "6. Work and Occupation" is selected, as well as selecting 6.7 or 6.2 specifically.  The only problem is where they occur vertically on the page.

**Comment by vernastutzman** [comment]
#1 is fixed, but #2 still needs attention.

**Comment by vernastutzman** [comment]
3. [FIXED] https://www.webonary.org/mp-tharu/browse/categories/?semdomain=Person&semnumber=2.&lang=en
Shows a mixture of Nepali and English Semantic domains. They need to be all in Nepali when the Nepali UI is picked and all in English when the English UI is picked.

**Comment by vernastutzman** [comment]
![image](https://user-images.githubusercontent.com/53490028/122647691-1dc0d200-d0eb-11eb-9feb-f96c2157578c.png)
