### ISSUE TITLE
Search Page with Special Characters

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#101]
https://www.webonary.work/ut-hun/
I tried clicking the “e-with-underscore” and then Search, and it said “No results”.  That seems wrong.
https://www.webonary.work/ut-hun?s=e%CC%B1&search=Search&key=&tax=&displayAdvancedSearchName=0

Then I clicked on the o-underscore.  The e-underscore was still in the box when I clicked, and when I clicked on the o-underscore, it was placed *before* the e-underscore in the search box (I would have expected “after”).  Then I clicked on u-underscore, and now that gets placed after the e-underscore.  Very non-intuitive.
Typed “a taag” in the search box, and then clicked on e-underscore, so I was searching for “a taage̱” which is definitely in the dictionary.  Again it said “No results”.
Pasted “a taage̱” into the search box and clicked Search.  “No Results” (wrong).
If I search for “taag”, then it does find “a taage̱”--that is good.
If I search for “a taag” that also finds “a taage̱”--that is also good.

FWBackup file in https://drive.google.com/drive/folders/1IDVEimJF05igvPLuShvguYeYY1fTzJEf

--

**Comment by bbryson** [comment]
Link for the folder with all backups for this round of testing:  [FLEx backups for testing](https://drive.google.com/drive/folders/1IDVEimJF05igvPLuShvguYeYY1fTzJEf?usp=sharing)

Link to the specific backup in that folder:  [Dukkawa 2020-06-26 1107 Jun26testing.fwbackup](https://drive.google.com/file/d/1NH4fwMrdpAZVikFh-PYhZ8iXho42D632/view?usp=sharing)

**Comment by hanatgit** [comment]
This is related to https://github.com/sillsdev/webonary/issues/96

**Comment by hanatgit** [comment]
Also, there is a problem when searching for multiple words, like "a taag". We need to ensure that the search is not done using fullsearch, which will handle the terms individually, but use a full equals search including space.
