### ISSUE TITLE
Some pictures did not upload

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#102]
Testing pictures, in the upload of Indonesian to https://www.webonary.work/test-bryson

My Indonesian database has pictures with several file extensions:  .png, .jpg, .jpeg.  Only the ones with .jpg uploaded successfully.  For the others, there is just an icon in place of the picture.
Entries with pictures:
  anjing  PNG, didn’t show
  burung PNG  didn’t show
  ikan  jpg did show
  inti  jpg  did show
  kucing  jpeg  didn’t show
  matahari jpg  did show
  nube  jpg  did show
  telur  png didn’t show

**Comment by bbryson** [comment]
Tested this again today.  This time I used:
FW 9.1.7.964  (so this should go to "the cloud", right?)
webonary.org
Project: Indonesian
Site: https://www.webonary.org/test-bryson

The .png and .jpeg pictures still do not show.  The .jpg pictures do show.

**Comment by vernastutzman** [comment]
Beth exported as xhtml file and all the pictures are in the file.
We're asking Ken Z to upload this project using the debugger.

**Comment by KenZook** [comment]
The uploaded files are all present in https://s3.console.aws.amazon.com/s3/buckets/cloud-storage.webonary.org?region=us-east-2&prefix=test-zook/pictures/&showversions=false

entry ikan with .jpg is stored in mongodb at {_id: "test-zook::g02dd592a-9a73-4aad-9557-5e48beaed4d7"}
The xhtml content for the picture is 
<span class=\"pictures\"><div class=\"picture\"><img class=\"thumbnail\" src=\"pictures\\Free-Fish-Clip-Art-GraphicsFairy.jpg\" id=\"g60fe41e2-bee5-43fb-9b00-edbb099c2298\" />

entry anjing with .png is stored in mongodb at {_id: "test-zook::gebcb7c05-d178-47c6-9c5c-8995dd93ba70"}
The xhtml content for the picture is
<span class=\"pictures\"><div class=\"picture\"><img class=\"thumbnail\" src=\"pictures\\intro-dog.png\" id=\"g5f425408-a77d-459a-b85f-f0dbb8216da0\" />

I don't see any place that Flex is failing. I assume that somewhere in webonary code it somehow maps to the correct s3 file during diplay on the dictionary view, and that code is missing .png and .jpeg options. A similar problem is blocking .mp4 files from working as well.

For the .jpg example, the displayed source is
<div class="picture"><img class="thumbnail" **src="https://s3.us-east-2.amazonaws.com/cloud-storage.webonary.org/test-zook/pictures/Free-Fish-Clip-Art-GraphicsFairy.jpg"** id="g60fe41e2-bee5-43fb-9b00-edbb099c2298"><div class="captionContent"><span class="headword"><span lang="id">ikan</span></span></div></div>

For the .png example, the displayed source is
<div class="picture"><img class="thumbnail" **src="pictures\intro-dog.png"** id="g5f425408-a77d-459a-b85f-f0dbb8216da0"><div class="captionContent"><span class="headword"><span lang="id">anjing</span></span></div></div>

Note the .png example is failing to translate the src.

**Comment by phillip-hopper** [comment]
Looking at the S3 bucket, all of the images were indeed uploaded. The "src" attribute of the images was not correctly set for some of them. 
![image](https://user-images.githubusercontent.com/5262964/145088654-8902e9d6-e39d-4f86-bbfc-0a6cfe607277.png)
