### ISSUE TITLE
Uploading file to Media Library

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#106]
I tried to Add/Upload a media file (Coordinator's Manual.pdf) and got the following error: Unexpected Response from the Server.

![Filename Issue](https://user-images.githubusercontent.com/53490028/87167804-2716ad00-c293-11ea-9053-42715e58d3d7.JPG)

It was possible to upload the file when I renamed it by removing the apostrophe and space from the filename.

**Comment by stevendyk** [comment]
File name restrictions depend on the operating system, but here is a good set of guidelines: 
https://www.mtu.edu/umc/services/digital/writing/characters-avoid/

**Comment by vernastutzman** [comment]
This issue can be closed.

**Comment by stevendyk** [comment]
This issue can be closed.
