### ISSUE TITLE
Provide indication in Webonary when a dictionary is being loaded to the cloud backend

### ISSUE THREAD

**Issue by hanatgit** [sillsdev/webonary#110]
In Webonary 1, a progress bar appeared in the Webonary plugin for dictionary admins while new data were being uploaded from FLex. In Webonary 2, no indication is given. Possible enhancements:

1. When FLex begins loading, put dictionary site in maintenance mode or give a message to pubic (optional), and provide a message to admins in the plugin dashboard
2. When FLex is completed, remove maintenance message

NOTE: Currently, at the end of  FLex upload, dictionary document is updated and Webonary site is notified through a hook, to update options. In this hook, #2 above can be done.

**Comment by stevendyk** [comment]
3. Han will develop a dashboard that will show status:

- which sites have been migrated to new database 
- which sites have zip files, which ones do not.

**Comment by vernastutzman** [comment]
Not needed.
