### ISSUE TITLE
Audio not working in Webonary

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#123]
![AudioFiles](https://user-images.githubusercontent.com/53490028/90650960-1d715500-e202-11ea-8ac2-4ab436f58a0c.JPG)
You can get to this page, https://www.webonary.org/obulom/browse/browse-vernacular/. Click on the Audio icons. No sound.

**Comment by stevendyk** [comment]
**_If_** this is caused by uploading an incompatible audio file type, @jasonleenaylor reports that this will be resolved in the next FLEX release. Reference [Github Combine Issue #623](https://github.com/sillsdev/TheCombine/issues/623)

**Comment by hanatgit** [comment]
Confirmed that the upload zip file does not contain any audio files. Marking it as a FLex issue.

**Comment by stevendyk** [comment]
Jason: to resolve this, we need to notify him of the file format (e.g. .ogg) of the audio files. He will then add it to the list of supported audio formats in FLEX.

**Comment by stevendyk** [comment]
Jason: to resolve this, we need to notify him of the file format (e.g. .ogg) of the audio files. He will then add it to the list of supported audio formats in FLEX. 
We need to: 

1. Notify Jason of the audio file format. 
2. After a new build is released, test and confirm this has solved the problem.

**Comment by stevendyk** [comment]
Need to 
1. coordinate with the author, determine what audio file format is used. 
2. Have Jason add this format to FLEX. 
3. When new FLEX version is available, have author re-upload with the latest FLEX version.

**Comment by vernastutzman** [comment]
This database has been uploaded successfully from Windows FLEx 9.1 and the audio files work (https://www.webonary.org/soskundi/browse/browse-vernacular-english/). So this remains a Linux upload problem.

**Comment by vernastutzman** [comment]
Have Anita send an email to the compiler of the Obulum Webonary site to ask to re-upload to check the audio files.

**Comment by vernastutzman** [comment]
The compiler of the Obulum Webonary site had a crashed computer and was not able to re-upload.
