### ISSUE TITLE
Not able to search by Semantic Domains in Sadri

### ISSUE THREAD

**Issue by stevendyk** [sillsdev/webonary#124]
On the Sadri Webonary site, [https://www.webonary.org/sadri/](https://www.webonary.org/sadri/), there are semantic domains in the entries, but the Semantic domains are not showing under Browse, Semantic Domains,  [https://www.webonary.org/sadri/browse/categories/](https://www.webonary.org/sadri/browse/categories/)

- Do you have to upload the Hindi Semantic Domain list or do something to make it connect in Webonary? 
- Is this specific to this orthography or site, or do all current uploads have this bug? 

![iddjmfgjfcnnalkg](https://user-images.githubusercontent.com/25255423/90797565-6a266000-e2d6-11ea-9c7c-c0174fbf75e2.png)

**Comment by stevendyk** [comment]
This is a result of invalid data upload. Specifically, the XML line needs to be removed. 

Action items:
Preferred: Verna will see if this data can be re-uploaded. However, this is no longer an active project 
Alternate: so, **Han will write a script to clean up the data.**

**Comment by stevendyk** [comment]
I just uploaded Tlingit to https://www.webonary.org/test-stutzman3/browse/categories/

This dictionary has a few semantic domains in it. When I go to the Semantic Domain Browse page, there is nothing, not even the list of Domains.

![kmjknjongfkocmmk](https://user-images.githubusercontent.com/25255423/92603540-0b208f00-f275-11ea-9834-5145d2071b70.png)

**Comment by stevendyk** [comment]
From team discussion: The Tlingit and Sadri examples are separate problems. Verna will create a separate issue for Tlingit.

**Comment by hanatgit** [comment]
Upon further research, it appears that Sadri was uploaded a long time ago before semantic domain numbers were used. Note that in https://www.webonary.work/sadri/wp-admin/edit-tags.php?taxonomy=sil_semantic_domains you can see that the Slug fields are not domain numbers.
![Screen Shot 2020-09-15 at 10 17 04 PM](https://user-images.githubusercontent.com/60716623/93289126-350d1080-f7a3-11ea-966c-d945134289fc.png)

Compare this other other more recent uploads, where slug field has domain numbers, like

![Screen Shot 2020-09-15 at 10 18 43 PM](https://user-images.githubusercontent.com/60716623/93289148-46eeb380-f7a3-11ea-8613-1a86e33a9add.png)

Looking at the code, if domain numbers are not present, then nothing is displayed on the semantic domains page.
So it seems like we should just remove the semantic domain page for this dictionary.

**Comment by stevendyk** [comment]
Verna reviewed, made the recommended change in Sadri.
