### ISSUE TITLE
Browse Page is duplicated halfway down the page

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#125]
![BalochiPageDuplication](https://user-images.githubusercontent.com/53490028/91215955-cf18f600-e6da-11ea-9adb-fef37ea9b42e.JPG)

https://www.webonary.org/balochidictionary/browse/?letter=%D8%B2&key=bcc

Every browse page on webonary.org/balochidictionary gets it contents listed twice. Click on any alphabet letter. Go halfway down the page and you’ll see the page start over again, complete with the header letter and the alphabet buttons.

**Comment by hanatgit** [comment]
This was due to the top menu level browse page incorrectly having the [vernacularalphabet] tag. The first child, correctly, also had it. Fixed by removing the tag in the browse page.
