### ISSUE TITLE
English reversal index does not display left to right in Balochi

### ISSUE THREAD

**Issue by stevendyk** [sillsdev/webonary#138]
[Verna] This page needs to be aligned along the left margin, [https://www.webonary.org/balochidictionary/browse/browse-english/](https://www.webonary.org/balochidictionary/browse/browse-english/)
![balochi-1](https://user-images.githubusercontent.com/25255423/92935341-47d3be00-f40e-11ea-8628-b09cf216156a.png)

 I can't tell that unchecking this box makes any difference.
![balochi-2](https://user-images.githubusercontent.com/25255423/92935358-4dc99f00-f40e-11ea-9a47-55edc7181947.png)

**Comment by phillip-hopper** [comment]
Most likely the text direction is not being explicitly set, so the browser is auto-selecting the alignment based on the characters detected.

**Comment by phillip-hopper** [comment]
After some research, I see the alignment is still explicitly set to Right in the on-page CSS.

![image](https://user-images.githubusercontent.com/5262964/93271044-56a8d080-f780-11ea-94f2-c379711273d7.png)
