### ISSUE TITLE
Can I reset a page / site that is displaying garbage without uploading again?

### ISSUE THREAD

**Issue by stevendyk** [sillsdev/webonary#142]
[Verna] Is there a way for me to reset a page that is displaying garbage without uploading again?
[https://www.webonary.org/faetar/browse/browse-faetar-english/](https://www.webonary.org/faetar/browse/browse-faetar-english/)
![faetar](https://user-images.githubusercontent.com/25255423/94700718-6b996e00-0301-11eb-8b68-290f66bff7ff.png)

**Comment by phillip-hopper** [comment]
Delete everything when:
1. Click delete button on webonary tab
2. New upload

**Comment by stevendyk** [comment]
Verna is clear on how to do this process manually. This is an infrequent process, there is no need to automate it at this time.
