### ISSUE TITLE
Messages of data not imported after loading data to new database

### ISSUE THREAD

**Issue by PaulNel** [sillsdev/webonary#152]
When the data is uploaded to the cloud database, errors related to old dictionary in Webonary are still present.

![image](https://user-images.githubusercontent.com/17054082/97327009-91535d80-1842-11eb-9ed2-9caba50963bc.png)

![image](https://user-images.githubusercontent.com/17054082/97327211-c3fd5600-1842-11eb-9fa8-25b82bc9a0be.png)

**Comment by hanatgit** [comment]
Shows date of last update and entries count now:

<img width="488" alt="Screen Shot 2020-11-03 at 8 58 01 AM" src="https://user-images.githubusercontent.com/60716623/98001019-c61b6380-1db2-11eb-81b0-8476274f4c22.png">

**Comment by stevendyk** [comment]
Nice!


<'}}}>< Steven Dyk | 469-619-5677 | stevendyk@gmail.com
<http://www.linkedin.com/profile?viewProfile=&key=5278730&locale=en_US&trk=tab_pro>

**Comment by vernastutzman** [comment]
This appears fixed. 12/18/20 - vps
