### ISSUE TITLE
update WordPress to latest version

### ISSUE THREAD

**Issue by stevendyk** [sillsdev/webonary#166]
![image](https://user-images.githubusercontent.com/25255423/104344945-61bc0500-54c3-11eb-84e3-1cc2eec15a7e.png)

1. Update webonary.work
2. Test webonary.work : needs to be tested with all plug-ins

3. Update webonary.org
4. Test webonary.org

**Comment by stevendyk** [comment]
Greg Mackay and Phil may use TeamCity to manage the upgrades.

**Comment by vernastutzman** [comment]
Sites are now updated. This is the current message. Not sure if it means anything.
![image](https://user-images.githubusercontent.com/53490028/122419081-49f41b80-cf50-11eb-83b6-545af3023ce1.png)

**Comment by phillip-hopper** [comment]
@vernastutzman I just ran the upgrade. Thanks for pointing that out. Sometimes when Wordpress releases an update fields are added to the database. That procedure makes sure all the tables are up-to-date.

**Comment by vernastutzman** [comment]
Great. That message has disappeared from the main site, but still showing on the subsites, https://www.webonary.work/kemedzung/wp-admin/
![image](https://user-images.githubusercontent.com/53490028/122618383-c3c0fd80-d053-11eb-9aa5-751f47370615.png)

**Comment by phillip-hopper** [comment]
Verna, I updated the .org site, the link you sent is from .work.

--
Phil Hopper
(937) 441-2616

**Comment by vernastutzman** [comment]
Looks like this issue can be closed.
