### ISSUE TITLE
failed upload with unusual user credentials

### ISSUE THREAD

**Issue by stevendyk** [sillsdev/webonary#168]
The site [https://www.webonary.org/doromu-koki/](https://www.webonary.org/doromu-koki/) fails uploads. 

Verna created a user ID with the email robert_bradshaw@sil.org. This should have created the user id robertbradshaw, but it created the id robbradshaw. 

Sites created with robbradshaw as the owner consistently fail uploads with the error 'Unable to connect to Webonary. Please check your user name and password'. Uploads fail when Robert uses his credentials, or Verna uses hers. 

Verna thinks that the user creation code is flawed, and would like a code review before she deletes and re-creates the user ID and site. 

[Verna's Test Notes](https://docs.google.com/document/d/1WcG2sFxl983KBn2qnvyKbbluG6VLLmT7_ducbbnidZk/edit?pli=1#heading=h.vryb6tj4p2wi)

**Comment by phillip-hopper** [comment]
It appears there are 2 sites for Doromu Komi.

![image](https://user-images.githubusercontent.com/5262964/105354437-8b111b00-5bbe-11eb-98ef-21771cbc50f3.png)

**Comment by phillip-hopper** [comment]
This is the user for the Wordpress backend.

![image](https://user-images.githubusercontent.com/5262964/105354571-bd227d00-5bbe-11eb-9eb4-ae4713667179.png)

**Comment by phillip-hopper** [comment]
And this is the user for the Cloud backend.

![image](https://user-images.githubusercontent.com/5262964/105354677-e4794a00-5bbe-11eb-9916-e4cac1c29a3d.png)

**Comment by vernastutzman** [comment]
I solved this by deleting the site, https://www.webonary.org/doromu-koki/, then re-creating it from https://www.webonary.org/doromukoki/. After that I was able to upload. No idea why we had trouble with the first https://www.webonary.org/doromu-koki/.
