### ISSUE TITLE
Sound files not working

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#175]
The sound files on the Sos Kundi Webonary site don't play, https://www.webonary.org/soskundi/browse/browse-vernacular-english/#gbdf355fc-c517-47ad-8f8b-452c217ecad0
![image](https://user-images.githubusercontent.com/53490028/109823263-623c6680-7bfd-11eb-8915-f447551f4688.png)

**Comment by vernastutzman** [comment]
The compiler has just re-uploaded and now the sound files don't work. She is using FLEx on a Linux OS. The sound files were in the correct folder on her machine, /home/correna/.local/share/fieldworks/Projects/Sos Kundi SDK/LinkedFiles/AudioVisual/aak.mp3.

**Comment by phillip-hopper** [comment]
I'm not familiar with the code, but I see why it isn't working. The URL of the page is 
```
https://www.webonary.org/soskundi/browse/browse-vernacular-english/
```
On the page the audio file is linked like this:
```
<audio id="some-id">
  <source src="AudioVisual/aak.mp3"/>
</audio>
```
which results in the URL of the audio file being 
```
https://www.webonary.org/soskundi/browse/browse-vernacular-english/AudioVisual/aak.mp3
```
The correct link would be this:
```
<audio id="some-id">
  <source src="/soskundi/files/AudioVisual/aak.mp3"/>
</audio>
```
which would point to the correct URL
```
https://www.webonary.org/soskundi/files/AudioVisual/aak.mp3
```

**Comment by vernastutzman** [comment]
[soskundi.zip](https://github.com/sillsdev/webonary/files/6086956/soskundi.zip)
Here is a zip file of what FLEx sent to Webonary. The code of interest is in the configured.xhtml file. It shows as line 3 in Notepad++.
Is FLEx writing it incorrectl? She just uploaded on March 2 and she is using the old Webonary system.

**Comment by vernastutzman** [comment]
The sound files are working now. The last Upload was April 7, 2021.
