### ISSUE TITLE
Search box - default language is blank

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#176]
![image](https://user-images.githubusercontent.com/53490028/109829073-d4fc1080-7c02-11eb-9589-9fbf91094460.png)

The default language box is blank when clicking on Advanced Search, https://www.webonary.org/cerma/?lang=en

**Comment by phillip-hopper** [comment]
It looks like this one crashed during the import. The status box says it stopped before importing reversals, but the Browse Views tabs shows 2 reversal indexes, both of them French.

**Comment by vernastutzman** [comment]
The Browse tab has the vernacular - Cerma and one reversal - French. 
![image](https://user-images.githubusercontent.com/53490028/122415447-8c682900-cf4d-11eb-94a6-68860acf1c58.png)
This dictionary was uploaded in 2014, so I'm not sure the compiler is available to upload again. Can you just fix this in this dictionary?

**Comment by vernastutzman** [comment]
Looks good.
