### ISSUE TITLE
Review SEO for Webonary

### ISSUE THREAD

**Issue by hanatgit** [sillsdev/webonary#18]
Listing of all the dictionary pages already exists at https://www.webonary.org/about-webonary/published-dictionaries/

Will need to evaluate current set up to see if crawlers are allowed, and if so, their impact on performance, as well as SEO.

**Comment by phillip-hopper** [comment]
I can confirm that crawlers are allowed, and Google has indexed that page.
![image](https://user-images.githubusercontent.com/5262964/94203494-809f7880-fe8d-11ea-9980-fb145874f1cb.png)

**Comment by phillip-hopper** [comment]
Google also has found a lot of dictionary sites, 374,000 results for webonary.org.
![image](https://user-images.githubusercontent.com/5262964/94203569-a4fb5500-fe8d-11ea-8745-dd5c9426c17f.png)

**Comment by phillip-hopper** [comment]
@hanatgit @vernastutzman @stevendyk Is the above information enough to close this issue, or is more needed? If more is needed, what exactly are we looking for?

**Comment by phillip-hopper** [comment]
FYI, Bing is also indexing the site, but not as extensively.
![image](https://user-images.githubusercontent.com/5262964/94204072-8cd80580-fe8e-11ea-86c2-c517e2a675cf.png)

**Comment by stevendyk** [comment]
Final review 21/01/13
