### ISSUE TITLE
Searching in the new database (upload with 9.1)

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#184]
Proper Searching has not been implemented for the new Mongo database.
Searching in a site (https://www.webonary.org/test-peacock2) uploaded from FLEx 9.0.* finds text basically in all fields.
Searching in a site (https://www.webonary.org/test-peacock1) uploaded from FLEx 9.1 only finds text that occurs in the main entry, not in subentries.

For example, "seeme" is a subentry for sí (to go). It also occurs in the English word 'seemed', in the gloss of kerka. It also occurs in as Daasanach in example sentences,  and part of "seemed in notes and translations of example sentences

test-peacock1(9.0) finds it under all of the above
test-peacock2(9.1)  finds it only as part of "seemed" in the gloss of kerka 

Check this document for more details:
https://docs.google.com/document/d/1Q5R5SJ3UwCo_7oImF8rJTohTPgaLyl_9r0g6FJd7OCA/edit

**Comment by vernastutzman** [comment]
https://docs.google.com/document/d/1Q5R5SJ3UwCo_7oImF8rJTohTPgaLyl_9r0g6FJd7OCA/edit?usp=sharing for more details.

**Comment by vernastutzman** [comment]
The Xavante webonary site has both sets of data: in Wordpress tables (9.0.14) and Mongo database (9.1).
https://www.webonary.org/xavante/gb4c56bd4-752d-4416-95f6-1782b051bb61/?lang=en
This site can be used for testing since searching subentries in the Wordpress tables works perfectly, but it does not work in the Mongo database.
Eduardo Soares <edurbs@gmail.com> is the contact person.

**Comment by johntseng** [comment]
Can you help me understand the move from WordPress SQL tables to Mongo? What was difficult with the SQL tables and/or what is Mongo enabling? Is the plan to migrate the WordPress sites to Mongo as well, or are we planning to duplicate the data in two different databases?

**Comment by phillip-hopper** [comment]
@johntseng message me in slack and I can give you more information.

**Comment by stevendyk** [comment]
John, I assume you have a more detailed response from Han. At the highest level, we moved from WordPress SQL tables for upload performance reasons, and to MongoDb on AWS because we want a consolidated dataset that will enable queries / displays for multiple languages / projects, and that was the preferred platform during the design phase for the migration.

**Comment by johntseng** [comment]
A few possible issues:
1. Flex didn't upload the entries
1. Lambda didn't accept the entries
1. Lambda didn't search correctly
1. PHP to Lambda connection doesn't ask for it correctly

**Comment by johntseng** [comment]
So far in my investigation, it looks like the dictionaries are totally different. There is no overlap between the two sets of search results.
![image](https://user-images.githubusercontent.com/4266917/166064005-d324a4b5-aa70-4620-8855-cfca5649d00c.png)
![image](https://user-images.githubusercontent.com/4266917/166064060-728883fb-7027-4e50-ba8b-608656dc7533.png)

Trying to get my hands on the uploaded datasets to see what's going on.

**Comment by vernastutzman** [comment]
[DSH 2021-04-13 0907 Gnr refs changed to SG_PL relations.fwbackup.zip](https://github.com/sillsdev/webonary/files/8604216/DSH.2021-04-13.0907.Gnr.refs.changed.to.SG_PL.relations.fwbackup.zip)
Remove the .zip extension before restoring the project.
This is the project that was uploaded to https://www.webonary.org/test-peacock2 (uploaded from FLEx 9.0.* finds text basically in all fields) and https://www.webonary.org/test-peacock1 (uploaded from FLEx 9.1 only finds text that occurs in the main entry, not in subentries).
It's the same project, but uploaded using different FLEx versions and going to different Webonary destinations, i.e. Wordpress tables vs. Mongo database. The goal is that the Search results on both sites should match the search results on https://www.webonary.org/daasanach/?lang=en or https://www.webonary.org/test-peacock1. Do you need a test site for uploading?
@johntseng

**Comment by johntseng** [comment]
I found a few issues:

1. When searching with the cloud API, [`matchPartial` is set to the same value as `match_whole_words`](https://github.com/sillsdev/webonary/blob/95f9f90f4857cb40173f76fda458bd623aeee66d/wp-resources/plugins/sil-dictionary-webonary/webonary/Webonary_Cloud.php#L382), which seems to be the opposite of what's supposed to happen. 
1. https://cloud-api.webonary.org/v1/get/entry/test-peacock1?guid=gdfb365e9-ce7a-4678-a53e-70904aaf4dcc has "seeme" as its headword according to `displayXhtml`, but its `mainHeadWord` field only has one empty head word.
1. Cloud API's full text index [only includes main headword and definition](https://github.com/sillsdev/webonary/blob/95f9f90f4857cb40173f76fda458bd623aeee66d/webonary-cloud-api/lambda/postDictionary.ts#L153), but Wordpress search also searches examples. Example: https://cloud-api.webonary.org/v1/get/entry/test-peacock1?guid=gb7f6d6e7-b43a-46ba-baee-2e6d854d67f2
1. There's a comment field in `displayXhtml`, but no comment in a [`DictionaryEntry`](https://github.com/sillsdev/webonary/blob/95f9f90f4857cb40173f76fda458bd623aeee66d/webonary-cloud-api/lambda/entry.model.ts). Example: https://cloud-api.webonary.org/v1/get/entry/test-peacock1?guid=g6cf4e3cb-29bb-41c7-84fc-37e90dfe4645 
1. There's a list of subentries in the `displayXhtml`, but there's no list of subentries in [`DictionaryEntry`](https://github.com/sillsdev/webonary/blob/95f9f90f4857cb40173f76fda458bd623aeee66d/webonary-cloud-api/lambda/entry.model.ts). Example: https://cloud-api.webonary.org/v1/get/entry/test-peacock1?guid=g74cc36a7-4917-4c1f-9d30-600b8a38eacd

**Comment by johntseng** [comment]
Issues 2-5 are mainly because the fields that the user selected are not part of the fields that we expected to be there.

After discussing with Jason and the team, I think we want to continue searching `displayXhtml` for the "search everywhere" feature that the 9.0 version has. For the future use cases of searching by particular fields, we will also do some custom coding to have some fallbacks, e.g. using the lexeme or citation form for entries that don't have a headWord.

**Comment by vernastutzman** [comment]
We uploaded the same database to https://www.webonary.work/test-peacock1/ (using FLEx 9.1.9) that had been uploaded to https://www.webonary.org/test-peacock2/ (using FLEx 9.0.*). Then we searched for 3 words, **seeme**, **baa** and **sien** on both Webonary sites and compared Search results. We did the comparisons having Match whole words checked and unchecked and with Match accents and tones checked and unchecked. On https://www.webonary.work/test-peacock1/ (using FLEx 9.1.9):

- Checking or unchecking Match accents and tones made no difference in Search results 
- There were missing results from Example Sentences, Notes, subentries, and headword
- The sort order of the Search results was not consistent, sometimes it was sorted, other times it was random
- Sometimes there were no search results returned, even though the word is in the dictionary.
- There is still a nonsensical message returned at times, "Because of the brevity of your search term, partial search was omitted."
- There is a case of highlighting not matching the Search item.

You may see our notes images of the comparison here: https://docs.google.com/document/d/1Pj1vJRxVlgG6dI6C8u7nyacBGi-PfosR7pT2tqGinyo/edit#.
