### ISSUE TITLE
Button delete dictionary data does not work

### ISSUE THREAD

**Issue by edurbs** [sillsdev/webonary#185]
I uploaded with FW 9.1.2 and now I'd like to delete the dictionary data, because the searching feature does not work and I'd like to upload again with FW 9.0.16
But button delete does not work, and so I can't upload again with FW 9.0.16.
![image](https://user-images.githubusercontent.com/16069975/117287699-0383ab00-ae41-11eb-956b-962db96968e6.png)

**Comment by vernastutzman** [comment]
You should be able to just upload using FLEx 9.0.16 without deleting the 
lexical data that you uploaded using 9.1. When you have done the upload 
with 9.0.16, send me a message and I will set the toggle in Webonary, so 
that you will be able to view the data from that upload. Then you can 
test to see if the Search results are working the way you want them to.

Verna

*Verna Stutzman, MA-Linguistics, MAC
Dictionary & Lexicography Services Coordinator
SIL International
Skype: verna.stutzman
Verna's Bio <http://www.sil.org/biography/verna-stutzman>*

Check out the online Dictionary-Making & Lexicography Course 
<https://sites.google.com/sil.org/dls-course/>

Sign up for the DLS newsletter 
<https://www.webonary.org/join-the-dictionary-lexicography-services-mailing-list/>

**Comment by edurbs** [comment]
@vernastutzman 
I made the upload yesterday with 9.0.16, so may you please set the toggle. Thank you very much.
