### ISSUE TITLE
.mp4 files cannot be uploaded from Flex 9.1

### ISSUE THREAD

**Issue by KenZook** [sillsdev/webonary#192]
This needs to be fixed in FW-20690 which includes a sample project.

**Comment by bbryson** [comment]
https://jira.sil.org/browse/LT-20690 was resolved today; maybe a nightly build of FLEx tomorrow would reflect the fix.

**Comment by vernastutzman** [comment]
It appears that water.mp4 was uplaoded to 
https://www.webonary.org/test-stutzman3/browse/browse-vernacular/?letter=e&key=fr , but it doesn't play.
Clicking on the icon takes me to this page, https://www.webonary.org/test-stutzman3/browse/browse-vernacular/AudioVisual/water.mp4. But no video.
