### ISSUE TITLE
Pages not right-aligned in Webonary even though right-aligned in FLEx

### ISSUE THREAD

**Issue by bbryson** [sillsdev/webonary#214]
Dictionaries that include both RTL and LTR text might be right-aligned or left-aligned.  In FLEx, it is possible to set the overall text flow for the page and the alignment in the Normal style.  

In my sample project, both right-alignment and left-alignment work correctly in FW 9.1.5.461 (7/23 build).  But when I upload to Webonary, the one that is right-aligned in FLEx comes out left-aligned in Webonary.

Sample files are in this folder:
https://drive.google.com/drive/folders/1VYis3SvS1f9WJEt8yci0PbrIscNuA2W2?usp=sharing

**Comment by bbryson** [comment]
Attaching pictures of what it looks like in FLEx.  First is RTL and second is LTR.  Both are working correctly:  the elements flow in the correct direction, and the alignment is correct.

<img width="563" alt="FW9 1 3-RTL-Fixed" src="https://user-images.githubusercontent.com/4039852/127222043-67f90bf8-abc6-47a0-88e9-73a1e3406809.png">
<img width="563" alt="FW9 1 3-LTR-StillWorks" src="https://user-images.githubusercontent.com/4039852/127222072-0bf6c0ea-a3ed-4bc0-b19c-cbf1518bd774.png">

**Comment by bbryson** [comment]
Attaching pictures of what it looks like in Webonary, uploading the same two views.

First is RTL and it flows right-to-left (good) but it is left-aligned (wrong).
Second is LTR and it works:  The elements flow left-to-right and it is left-aligned.

<img width="565" alt="Webonary-RTL-WrongAlignment" src="https://user-images.githubusercontent.com/4039852/127222629-83bbdc39-a65e-4185-98cb-e10833b68011.png">

<img width="565" alt="Webonary-LTR-Works" src="https://user-images.githubusercontent.com/4039852/127222621-8721d5a0-bb56-4d65-8b80-2b935f6eda5b.png">

**Comment by bbryson** [comment]
Is this just as simple as ticking the box for "display right-to-left" in the Browse Views tab of the Dashboard?  Is the overall page flow set there, instead of in the CSS?  Is there any interaction between the two?

**Comment by stevendyk** [comment]
Verna: We can close this issue.
