### ISSUE TITLE
Apparently insecure use of wildcards

### ISSUE THREAD

**Issue by LVSant** [sillsdev/webonary#215]
Our research team at Tenchi found some apparently insecure use of wildcards `(*)` in your Custom Lambda Authorizer. Precisely [here](https://github.com/sillsdev/webonary/blob/a64f1be588c77c189d788785a2a0fe451ed49966/webonary-cloud-api/lambda/methodAuthorize.ts#L63). When you use wildcards anywhere in policies resources other than in the very end and after a slash, you're very likely to be allowing your users to access more API endpoints than you intended. This is because the wildcard `(*)` doesn't stop expanding at slashes `(/)`, as the AWS documentation stated up until very recently. For clarification, please check out our blog post about the subject at [Tenchi Security](https://www.tenchisecurity.com/blog/thefaultinourstars)

**Comment by stevendyk** [comment]
Reviewed with developers, concluded that we are secure.
