### ISSUE TITLE
L2R languages having right-justified margin

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#245]
On sites with a mixture of L2R and R2L languages, the L2R pages should be left-justified and the R2L pages should be right-justified.
https://www.webonary.org/template-urdu/en/
![image](https://user-images.githubusercontent.com/53490028/143273943-409c6d4d-0acd-432e-be12-753c190d3da1.png)

**Comment by phillip-hopper** [comment]
Webonary is conflating the vernacular and user-interface languages. The solution is to make another template that takes this into account. The current template was probably not designed for what we need it to do today.
