### ISSUE TITLE
Landing page statistics

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#246]
Only list languages that actually have entries on Webonary. Don't list an unnamed language with 0 entries.
![image](https://user-images.githubusercontent.com/53490028/143912043-7f9ca638-03ea-4dd8-97cf-3fbaa12fa894.png)

**Comment by phillip-hopper** [comment]
In `webonary-cloud-api/lambda/dictionary.model.ts` the `reversalLanguages` value is being initialized to an array with a single empty element. The true fix will be to update the typescript so that doesn't happen.

```typescript
  constructor(dictionaryId: string, updatedBy?: string, updatedAt?: string) {
    this._id = dictionaryId;
    this.updatedBy = updatedBy ?? '';
    this.updatedAt = updatedAt ?? new Date().toUTCString();

    // Set initial values so we can do Object.keys for dynamic case-insensitive copying
    this.mainLanguage = new LanguageItem();
    this.reversalLanguages = Array(new LanguageItem());
    this.partsOfSpeech = Array(new ListOptionItem());
    this.semanticDomains = Array(new ListOptionItem());
  }
```
