### ISSUE TITLE
Change English SD 9.2.8 in Webonary to Onomatopoeic words

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#252]
From Kevin - I think Phil needs to update 9.2.8 in Webonary to "Onomatopoeic words". Then it will be in sync with FLEx again, and he should have no further problems importing the domain names for the other languages.

**Comment by vernastutzman** [comment]
Don't change to Onomatopoeic words.
Change to Ideophones with the correct spelling.

**Comment by stevendyk** [comment]
Reviewed and closed on 4/19 team meeting
