### ISSUE TITLE
Changes for the Russian UI

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#261]
Change text on this button
![image](https://user-images.githubusercontent.com/53490028/144935388-61b5f417-ece6-4263-8686-80bdf367377e.png)
to **поиск**
https://www.webonary.org/tsakhur?s=aazir&search=%D0%98%D1%81%D0%BA%D0%B0%D1%82%D1%8C%2C+%D1%80%D0%B0%D0%B7%D1%8B%D1%81%D0%BA%D0%B8%D0%B2%D0%B0%D1%82%D1%8C&key=&search_options_set=1&match_whole_words=1&displayAdvancedSearchName=0&lang=ru
![image](https://user-images.githubusercontent.com/53490028/144935642-dbf02393-f619-469b-98a2-3123603a876e.png)

**Comment by vernastutzman** [comment]
Looks good.

**Comment by stevendyk** [comment]
Closed on 4/19 team meeting
