### ISSUE TITLE
FLEx stylesheet should be limited to lexical data

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#288]
On https://www.webonary.org/dari/, there is red text under number of entries the alphabet header and the Publication status. Apparently this is because the default color in the FLEx stylesheet is red. The FLEx stylesheet should have nothing to do with this page. It is only for the lexical data. Webonary should be in control of the look and feel of the landing page.
![image](https://user-images.githubusercontent.com/53490028/149367658-e961a2d7-3d8c-48ab-9ac9-d1403113cc25.png)

**Comment by vernastutzman** [comment]
I bet it's because English is the vernacular in this case. I have not seen this behavior on other sites, but then English is not usually the vernacular.

**Comment by vernastutzman** [comment]
When the compiler changed English, the vernacular language in FLEx to black and uploaded, the landing page was in black:
![image](https://user-images.githubusercontent.com/53490028/149536284-5ed21f99-7b16-42a3-bf7e-5647298d939e.png)

**Comment by vernastutzman** [comment]
The Upload from 9.0 and 9.1 works differently in regards to the stylesheet. This issue appears to not be a problem with uploading from 9.1. This may need to be tested in the future.

**Comment by peteroatley** [comment]
I looked at the site and the last upload is October 24 2023. The page is still black in colour.
