### ISSUE TITLE
The Grammars page doesn't show the hyperlinks, date header

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#292]
On this page, https://www.webonary.org/wp-admin/post.php?post=1037&action=edit, the code: 
"[gdoc key="https://docs.google.com/spreadsheets/d/167vaQ7RPqcWZSGDxtg1btgDc9ktTJEQMN0Da3C5mDQM/edit?ts=5c92827a#gid=0" query="select A, B, C, D, E, F"]"
 doesn't show the links, which are in the following spreadsheet, 
https://docs.google.com/spreadsheets/d/167vaQ7RPqcWZSGDxtg1btgDc9ktTJEQMN0Da3C5mDQM/edit#gid=0

The date column does not show a header.

**Comment by peteroatley** [comment]
Another problem is that the 6th column is missing and when using a different layout which shows all columns its header is missing.

The page uses this plugin to display the spreadsheet.

https://wordpress.org/plugins/inline-google-spreadsheet-viewer/#other_notes

It looks like the plugin is not processing the header information correctly. There are similar problems mentioned in the support forum but I couldn't get any of the suggestions to work. 

The Google Sheet has a header row which might be causing a problem needs testing.

I don't think it can handle linked URLs and the field would need to have the actual URL link.

The plugin has not been updated for a few years and may now be incompatible with WP. However it still gets positive reviews and has a lot of users. There don't seem to be many other plugins which just focus on displaying Google Sheets and which have such good functionality.

Are there any other pages which use this plugin?

Here are some plugin options:

https://wordpress.org/plugins/tablesome/ - mainly for sending data from forms to Google but can also display tables.

**Comment by peteroatley** [comment]
After discussion it was decided that a better solution would be to have a table of links and whenever a Grammar page is created add a link to that page to the table. The table would be displayed on the Grammar summary page (https://www.webonary.org/grammars/).

The grammar link should only be added for dictionaries with the Published Status. The Grammar page should be checked to make sure that it isn't the default blank page. The default page has the following text: "Use this page to provide information about the Grammar of the language, either directly, or as a link or as a download."

The table should contain the same or similar information to the Google sheet.
https://docs.google.com/spreadsheets/d/167vaQ7RPqcWZSGDxtg1btgDc9ktTJEQMN0Da3C5mDQM/edit?pli=1#gid=0

**Comment by peteroatley** [comment]
After further discussion we decided to create the information programmatically. I have created a new issue for this.
