### ISSUE TITLE
Additional Spanish UI translations

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#293]
Here are some additional Spanish equivalents for the Spanish UI.
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/VERNAS~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/VERNAS~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

  |   |  
-- | -- | --
Search |   | Buscar
Advanced Search |   | Búsqueda avanzada
Hide Advanced Search |   | Ocultar búsqueda avanzada
Match whole words |   | Coincidir palabras completas
Match accents and tones |   | Coincidir acentos y tonos
Southeastern Tepehuan |   | Tepehuán del sureste
Spanish |   | Español
Last update |   | Última actualización
SIL Mexico |   | SIL en México

</body>

</html>

Some of these terms appear on the landing page:
<img width="236" alt="image" src="https://user-images.githubusercontent.com/53490028/151565303-762ab92e-6e72-46b2-ab67-c3456f1e8dec.png">

https://www.webonary.org/tepehuan-sureste/?lang=es#

**Comment by vernastutzman** [comment]
Unless you find something in the Spanish list, use Fecha de publicación: for Date published:

**Comment by vernastutzman** [comment]
Last update was missed:
![image](https://user-images.githubusercontent.com/53490028/157062795-326c6e4a-eb4c-40e9-98de-b48e4912ea9d.png)
From the chart above, it should be: Última actualización.

**Comment by stevendyk** [comment]
closed on 4/19 team call
