### ISSUE TITLE
Publication - Add Links to main Webonary page

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#294]
I added Meid to add https://www.webonary.work/meid/ to the https://www.webonary.work/wp-admin/link-add.php to publish it on webonary.work. (
![image](https://user-images.githubusercontent.com/53490028/152057990-45346455-0a52-40c1-8640-4971c2d63629.png)
)
It said it was added, but when I went to the website, it did not give the Date Published, 
![image](https://user-images.githubusercontent.com/53490028/152058177-055342c5-a2b3-451a-a216-b7bd925908e7.png)
When I went to Add Links to Map, https://www.webonary.work/wp-admin/link-manager.php?page=links-map-publish%2Flinks-map-publish.php, there were no coordinates in the Latitude and Longitude boxes. It used to get these coordinates from Ethnologue.

![image](https://user-images.githubusercontent.com/53490028/152057771-e4e59c04-875d-4e4f-a97b-8c580e834339.png)

**Comment by peteroatley** [comment]
Publishing now working.
