### ISSUE TITLE
Webonary not honoring digraphs in Shoebox short order

### ISSUE THREAD

**Issue by indiamcq** [sillsdev/webonary#305]
In the sorting does not recognize the digraphs defined in the Shoebox sort order in Flex. 
Also the alphabet buttons don't recognize the sort order and digraphs.
![image](https://user-images.githubusercontent.com/1505640/157669896-57d99198-e2aa-47db-af82-3113a3772874.png)
The sort order is:
```
Aa aa
A a
Ii ii
I i
K k
L l
Rl rl
Ly ly
M m
N n
Rn rn
Ng ng
Ny ny
P p
R r
Rr rr
T t
Rt rt
Tj tj
U u
Uu uu
W w
Y y
```
The rl and rn occurring before the normal r position messes up the order.

**Comment by peteroatley** [comment]
This has been fixed in Flex. I created a test dictionary and uploaded it to Webonary and it displayed the digraphs correctly.
