### ISSUE TITLE
Pins are not showing on the map

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#322]
![image](https://user-images.githubusercontent.com/53490028/166735234-dc9ab725-e1f3-4717-b1c7-444633848e97.png)
For example, Brazil should have pins for: Ninam (https://www.webonary.org/ninam/) and Xavante (https://www.webonary.org/xavante/), but I can't find them. Webonary is using these coordinates:
![image](https://user-images.githubusercontent.com/53490028/166737383-f5276084-3561-4598-8cd2-67ec2fdb14a1.png)

![image](https://user-images.githubusercontent.com/53490028/166737740-e424bba9-56af-4ba7-a26d-e5330548386f.png)

**Comment by vernastutzman** [comment]
Is there a way to reconcile the number of pins to the number of languages with coordinates? There should be 275 pins.

**Comment by peteroatley** [comment]
This has been addressed in #610
