### ISSUE TITLE
Partial search is not working in cloud-enabled site

### ISSUE THREAD

**Issue by hanatgit** [sillsdev/webonary#323]
When searching a cloud-enabled dictionary, `Match whole words` is working opposite of what it was intended.

For example, searching for `naa` without setting `Match whole words` result in no results, `https://www.webonary.org/test-chung?s=naa&search=Search&key=&tax=&search_options_set=1&displayAdvancedSearchName=1&lang=en

<img width="1216" alt="Screen Shot 2022-05-13 at 3 01 36 PM" src="https://user-images.githubusercontent.com/60716623/168381635-546a9977-d2ad-4512-b217-a1fdaf4c23c1.png">

But searching with 'Match whole words' clicked finds the partial word matches, https://www.webonary.org/test-chung?s=naa&search=Search&key=&tax=&search_options_set=1&match_whole_words=1&displayAdvancedSearchName=1&lang=en
<img width="1105" alt="Screen Shot 2022-05-13 at 3 04 40 PM" src="https://user-images.githubusercontent.com/60716623/168381796-30471d19-4398-418c-82c6-54dc52da2716.png">

[See https://github.com/sillsdev/webonary/issues/184#issuecomment-1123053687], where it was uncovered.

**Comment by johntseng** [comment]
Han, I thought you submitted a pull request for this fix. I don't see it anymore. Was I just imagining it? https://github.com/sillsdev/webonary/blob/develop/wp-resources/plugins/sil-dictionary-webonary/webonary/Webonary_Cloud.php#L382

**Comment by hanatgit** [comment]
PR has been approved, and has been deployed and tested in webonary.work
