### ISSUE TITLE
Upload Ginger's 10-glot in French and English

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#335]
Please upload Ginger-format-master-language-french.html to https://www.webonary.org/mbam/browse/francais/?lang=en and Ginger-format-master-language-english.html to https://www.webonary.org/mbam/browse/browse-english/?lang=en. The files were sent by email as Github didn't allow html files to be uploaded.

**Comment by phillip-hopper** [comment]
The files are too large to use the Tiny MCE editor

**Comment by phillip-hopper** [comment]
These are the steps I used to fix and shrink the files:

1. Replace `<?xml version="1.0" encoding="UTF-8"?>` with `<!DOCTYPE html>`
2. Replace `<html:` with `<`
3. Replace `</html:` with `</`
4. Replace `<html xml.*\s.*>` with `<html lang="en">`
5. Replace ` rowspan="1"` with ``
6. Replace ` colspan="1"` with ``
7. Replace ` shape="rect"` with ``
8. Replace `href="http://Webonary.org/` with `href="/`
9. Replace `href="/(.+\?s=) (.+?)"` with `href="/\1\2"`  [remove leading space]
10. Replace `<a (.+?)>\s+(.+?)</a>` with `<a \1>\2</a>`  [remove leading space]
11. Replace ` </a><br/>` with `</a><br/>`  [remove trailing space]
12. Replace `<tr id=".+?"` with `<tr`  [remove id]
13. Replace `\n\s*<title/>\n` with `\n`
14. Replace `table tr.even {background: #ffffff; }` with `table tbody tr:nth-child(odd) td {background: #ffffff;}`
15. Replace `table tr.odd {background: #ddf2fb; }` with `table tbody tr:nth-child(even) td {background: #ddf2fb;}`
16. Replace `table tr td.lx {font-weight:bold; background: yellow; text-align: center;}` with `table tbody tr td:first-child {font-weight:bold;background: yellow;text-align: center;}`
17. Replace ` class="even"` with ``
18. Replace ` class="odd"` with ``
19. Replace ` class="lx"` with ``
20. Replace `table {width: 100%}` with `table {width: 100%;border-collapse: collapse;}`
21. Replace `^\s+` with ``  [remove blank space from beginning of lines]

**Comment by vernastutzman** [comment]
Ginger found a lot of mistakes in Jim's spreadsheet, so she is doing a lot of editing. Then Jim will recreate the file and we'll have to upload it again. I told them they had only one more shot at it. So I don't really want to close this yet.

**Comment by vernastutzman** [comment]
Ginger seems happy with the way things are now.
