### ISSUE TITLE
UI localization

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#34]
Currently, when giving the user the ability to, for instance, upload a file, the HTML code for uploading the file has to be specified once for each UI language.  It should only be specified once, and used in all versions of the UI.
	There are also strings that are used in more than one place, that currently need to be typed in each place.  Better to type them in only one place.

**Comment by vernastutzman** [comment]
An example where French does not show up in the Publication status, https://www.webonary.org/phuien/?lang=fr
.

**Comment by stevendyk** [comment]
Closed after review on 4/19 team call
