### ISSUE TITLE
Remove underlines from the alphabetic characters

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#365]
![image](https://user-images.githubusercontent.com/53490028/179852091-c60a76f4-8541-4202-953c-071894ac0200.png)
The Alphabetic characters on the landing page and the browse page don't need an underline to show that it's a link. In some languages there are underlines under the letters themselves, so it makes it hard to distinguish between regular d and underlined d, for example.

**Comment by phillip-hopper** [comment]
It's on this page also: https://www.webonary.work/sahu/browse/browse-vernacular-english/?lang=en

**Comment by vernastutzman** [comment]
All undesirable underlines are gone.

**Comment by vernastutzman** [comment]
successful on .org
