### ISSUE TITLE
[vernacularalphabet] returns nonsense

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#366]
When the alphabet characters are missing for any reason, then [vernacularalphabet] returns nonsense.
![image](https://user-images.githubusercontent.com/53490028/179854511-330bf33e-ad95-4730-91e5-86fafb3c359d.png)

This is because of this code:
SELECT SQL_CALC_FOUND_ROWS ID, post_content
FROM wp_314_posts
WHERE post_content_filtered = ''

If the alphabet character is missing, [vernacularalphabet] should either return an error message or nothing.

**Comment by phillip-hopper** [comment]
Duplicates #363

**Comment by phillip-hopper** [comment]
Duplicate of #363
