### ISSUE TITLE
Add "Display right-to-left" check box for "Special character input buttons"

### ISSUE THREAD

**Issue by phillip-hopper** [sillsdev/webonary#375]
Also make the text box width 100%

![image](https://user-images.githubusercontent.com/5262964/183753905-dbfcdd81-e825-4d6a-980a-73e05df16abf.png)

**Comment by vernastutzman** [comment]
The font size on the buttons should be larger and easier to see. 
![image](https://user-images.githubusercontent.com/53490028/183758558-4a7cd2cc-e7ce-4502-a26d-970f1b7c9093.png)

**Comment by vernastutzman** [comment]
1. The buttons in this box should right align when the text is right2left and left align when it is left2right.
2. Can we choose the Font size as well as the font?

**Comment by vernastutzman** [comment]
Check this on https://www.webonary.org/dari/.

**Comment by vernastutzman** [comment]
When R2L characters were added separated by R2L commas, this is what happened.
![image](https://user-images.githubusercontent.com/53490028/185195014-59e6d84a-9772-48fa-bed0-75df43443831.png)

**Comment by vernastutzman** [comment]
successful in .org.
Need to research other language commas.
