### ISSUE TITLE
Add publishing info to Dictionaries in the Mongo Database

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#395]
To prepare for future searching across dictionaries in the Mongo database, each dictionary needs to know if it is published. "Published" means that it has been added to the dropdown list on the landing page, https://www.webonary.org/. The reason for this is that we don't want to return any data from unpublished sites during cross dictionary searches, since we have not been given permission to make that data public.
The dictionary should know its published date and perhaps its last upload date, since that might give an idea of how current the data is.

**Comment by peteroatley** [comment]
Looking at display-all-sites, dictionaries on MongoDB have a publish date and last upload date.

Dictionaries without a publication data don't show up on a DuckDuckGo search.

**Comment by stevendyk** [comment]
Reviewed 11/8/23, in production
