### ISSUE TITLE
The word selected off of the suggestion banner of a Keyman keyboard on mobile devices doesn't get searched in webonary.org

### ISSUE THREAD

**Issue by MakaraSok** [sillsdev/webonary#399]
Webonary seems to only ignore regular spaces in the search box, but not the ZWSP. 
When search for:
1. នតាម់ with a regular space, i.e. "នតាម់ ", the expected result is shown:
<img width="700" alt="image" src="https://user-images.githubusercontent.com/28331388/187345995-5835edf7-0d11-4996-9c42-07bb16c4dd5b.png">

2. នតាម់ with a zero width space, i.e. "នតាម់​", the expected result is not shown:
<img width="700" alt="image" src="https://user-images.githubusercontent.com/28331388/187345833-652ce34d-89aa-47b6-8ba1-1b905f19f75f.png">

It might be helpful to ignore ZWJ and ZWNJ as well in the search box to avoid missing search result.

Related issue: https://github.com/keymanapp/keyman/issues/7141

**Comment by mcdurdin** [comment]
This really feels like a 'normalization' step similar to how you'd normalize to NFC before search. Stripping whitespace on both input and search keys means that you may get some additional results but in general should give better outcomes. YMMV. There is a lot of data out there on good Unicode approaches to normalizing text before search. The best starting point on this might be https://www.w3.org/TR/charmod-norm/ (https://www.w3.org/TR/charmod-norm/#invisibleCharacters for text relating specifically to this use case.)

**Comment by vernastutzman** [comment]
Confirmed working in .work and .org https://www.webonary.work/bunong/en/.
