### ISSUE TITLE
Use cloud backend data in display-all-sites page and Excel export file

### ISSUE THREAD

**Issue by hanatgit** [sillsdev/webonary#401]
Per discussion with Verna:
- display number of entries and last upload for cloud backend dictionaries
- change label from "Last Import" to "Last Upload"
- show whether data is from Wordpress or Cloud backend

Also, the label "Last Import" that appears below the Search form should also be changed to "Last Upload"

**Comment by vernastutzman** [comment]
![image](https://user-images.githubusercontent.com/53490028/191359523-64831257-a1ba-4ec9-90ab-b640fb3fa7db.png)
Since Notes can be a very wide column, please move Last Upload to appear before Notes.

**Comment by phillip-hopper** [comment]
It appears work on the original issue is complete. I added #422 for rearranging the columns, and I'm closing this issue.
