### ISSUE TITLE
Edits for the Search & Statistics for https://www.webonary.org/semai/

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#419]
1. Here are the equivalents for the labels in Malay and Semai for the Search and Statistics area. Please use the date format of DD-MMM-YYYY for all 3 languages.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/VERNAS~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/VERNAS~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#1155CC" vlink="#1155CC">

English | Malay | Semai
-- | -- | --
Number of Entries | Jumlah   Entri | Jumlah   Entri
Last update | Kemaskini   Terakhir | Kemaskini   Terakhir
Date Published | Tarikh   diterbitkan | Tarikh   Biterbit
<order of the date (British way)>     DD Month YYYY | DD   Month YYYY | DD   Month YYYY
January | Januari | Januari
February | Februari | Februari
March | Mac | Mac
April | April | April
May | Mei | Mei
June | Jun | Jun
July | Julai | Julai
August | Ogos | Ogos
September | September | September
October | Oktober | Oktober
November | November | November
December | Disember | Disember

</body>

</html>

2. The language name is Malay, NOT Malay (macrolanguage)

**Comment by phillip-hopper** [comment]
- The date formats are pulled from the language code, we don't have a setting for that.
- The month names are pulled from the language code, we don't translate those in Webonary.
- The language name was probably pulled from FLex, but they can change it easily in the wp-admin.

**Comment by phillip-hopper** [comment]
The language code for Semai was set to "se", which is the code for "Sami (Northern) (Sweden)". I believe the correct code is "sea" (https://en.wikipedia.org/wiki/Semai_language). I will use the locale code "sea_MY".

After more research, it appears the Semai language is not included in the list of locales for anything (PHP, Linux, Windows, etc). I can copy the ms_MY localization file for Webonary and use it for the Webonary strings, but the date formatting will be a problem.
