### ISSUE TITLE
Delete data from Test site

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#420]
Add a feature to the Admin dashboard to remove data from a test site (or any site) so that the site can be preserved for testing another time, but the test data does not need to sit on the server after it has been looked at.

**Comment by vernastutzman** [comment]
I attempted to delete Webonary data on my test site, https://www.webonary.org/test-stutzman9/wp-admin/admin.php?page=webonary. This is the message I got:
![image](https://user-images.githubusercontent.com/53490028/218529244-c859392d-d087-40a7-becf-2e619acb3ae4.png)

**Comment by phillip-hopper** [comment]
@vernastutzman Are you able to delete the data on the test server?

**Comment by vernastutzman** [comment]
I get the same message "Not able to delete Webonary data".
on https://www.webonary.work/test-stutzman9/browse/browse-vernacular/
![image](https://user-images.githubusercontent.com/53490028/219180309-65cbcb44-429c-416f-a024-fbd34a62d4d3.png)

**Comment by stevendyk** [comment]
Verna tested: unable to verify

**Comment by hanatgit** [comment]
Confirmed data is deleted in MongoDb, @vernastutzman @stevendyk
