### ISSUE TITLE
Alphabetize the Parts of Speech in the Dropdown box in the Search widget

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#421]
![image](https://user-images.githubusercontent.com/53490028/192638629-6d0f7d54-3b85-4ada-8641-42ed01bc9b59.png)
https://www.webonary.work/test-peacock1/

**Comment by vernastutzman** [comment]
Allow the user to select all the Verb types, that is Complex Verb, Compounded Verb, and Copular Verb for one search on entries that have a verb part of speech.

Site for testing, https://www.webonary.org/odissi/
https://www.webonary.org/akoose/

**Comment by phillip-hopper** [comment]
@vernastutzman, I made a new issue for the multi-select, Issue #447

**Comment by stevendyk** [comment]
Verna: works now in production.
