### ISSUE TITLE
Consider updating the Contact Form 7 Database plugin

### ISSUE THREAD

**Issue by phillip-hopper** [sillsdev/webonary#431]
It looks like there has been a recent release that addresses PHP 8.1 compatibility.

https://github.com/mdsimpson/contact-form-7-to-database-extension/releases

**Comment by vernastutzman** [comment]
I tried to send a message using the Contact form here: https://www.webonary.work/test-stutzman/help/contact-us/#wpcf7-f369464-p9449-o1

I got an error each time:
![image](https://user-images.githubusercontent.com/53490028/207116226-97beb1d2-c427-4c4c-b6c9-aa5e704b8800.png)
