### ISSUE TITLE
paging does not work after a search is done in Webonary

### ISSUE THREAD

**Issue by hanatgit** [sillsdev/webonary#44]
Page links do display, but each of the pages contain the full search results.

**Comment by hanatgit** [comment]
See https://www.webonary.org/moore?s=person&search=Search&key=&tax=-1&displayAdvancedSearchName=0&lang=en
as an example.

**Comment by phillip-hopper** [comment]
@hanatgit, The WordPress API documentation seems to indicate the `posts_filter` hook should include the paging code also. https://codex.wordpress.org/Plugin_API/Filter_Reference/posts_request
