### ISSUE TITLE
Allow multi-select in the part-of-speech dropdown

### ISSUE THREAD

**Issue by phillip-hopper** [sillsdev/webonary#447]
Allow the user to select all the Verb types, that is Complex Verb, Compounded Verb, and Copular Verb for one search on entries that have a verb part of speech.

Sites for testing:

- https://www.webonary.org/odissi/
- https://www.webonary.org/akoose/

**Comment by johntseng** [comment]
The cloud API portion of this will be done in #450

**Comment by vernastutzman** [comment]
Would it be possible to have a scroll bar in the dropdown box like this:
![image](https://user-images.githubusercontent.com/53490028/207724077-f00d18c0-0353-44db-8a62-1fd1a7808859.png)
