### ISSUE TITLE
Check published sites for data

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#45]
Create a routine that checks published sites to see if they still have lexical data. Sometimes users remove the data without telling us. We don't want published sites with no lexical data.

**Comment by peteroatley** [comment]
The display-all-sites report shows the number of entries and the column can be sorted to bring all the zero entry dictionaries to the top. Is this sufficient?

**Comment by vernastutzman** [comment]
@peteroatley 
Maybe.
