### ISSUE TITLE
No Parts of Speech Dropdown box-why?

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#455]
Why is there no Part of Speech dropdown box here, https://www.webonary.work/test-stutzman?s=af%C9%9B&search=Search&key=mql&search_options_set=1&match_whole_words=1 
Latest upload Nov 29th.

**Comment by phillip-hopper** [comment]
@vernastutzman this is because the parts of speech are all French and the site language is English. 

I have a pull request in that should help, but the list will be in a different language.

**Comment by stevendyk** [comment]
Verna confirmed to working in .work, so this is ready to move to production.
