### ISSUE TITLE
Enable comments on individual entries

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#485]
Re-enable comments on individual entries for Cloud data. The comment should be sent by email to the Admin email on file.

![image](https://user-images.githubusercontent.com/53490028/214873229-6da7850e-aecc-42d8-8f70-bfcc9b2d747c.png)

**Comment by vernastutzman** [comment]
For the Tama webonary page (webonary.org/tama), how can I get comments turned on?  I would like people to be able to leave feedback on entries easily. From Dave Redford

**Comment by phillip-hopper** [comment]
Duplicates #426
