### ISSUE TITLE
Reversal Index Sort Order

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#497]
When there is more than one Reversal Index, the sort order for both indexes seems to be taken from the first Reversal that uploads.
I was testing sort orders and I reversed the sort order for the English reversal in FLEx, leaving the Spanish one correct, but after uploading, both Reversal Indexes were reversed. Refer to when the Entry Count for Reversal indexes was taken from the first Reversal Index that uploaded.

https://www.webonary.org/test-stutzman/browse-indonesian/
![image](https://user-images.githubusercontent.com/53490028/215574301-69cd944c-a055-434d-af2a-d6d937e71e85.png)

https://www.webonary.org/test-stutzman/browse/browse-english/
![image](https://user-images.githubusercontent.com/53490028/215574832-b1fa3f1e-2704-429a-a805-2e4ebe927440.png)

**Comment by hanatgit** [comment]
@vernastutzman This is how FLex is sending the reversal order. So it appears that FLex is sending the wrong order. Once this is fixed in FLex, and the data is reuploaded to Webonary, it should work correctly.
