### ISSUE TITLE
Use FLEx-defined word-forming characters to determine word boundaries for Searching

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#500]
When searching by Whole word, word-forming characters as defined in the FLEx project should be used to determine word boundaries.

Search Results in Webonary: https://www.webonary.org/phuien?s=ba&search=Search&key=pug&pos=&semantic_domain=&search_options_set=1&match_whole_words=1&lang=en

The five entries marked with the red line do not match what was searched for as a whole word, since the hyphen is a word forming character, not punctuation.
![image](https://user-images.githubusercontent.com/53490028/215804259-cc3db279-c225-4e9a-aa40-5c3ea4d0c6e3.png)

In the FLEx project, the hyphen is clearly identified as a word-forming character:
![image](https://user-images.githubusercontent.com/53490028/215805202-87cc5012-17da-416d-b452-4ac3b159f12c.png)

**Comment by hanatgit** [comment]
@vernastutzman Currently FLex sends letter heads for each dictionary. Would that be a reliable way to determine word forming letters? Or do we need to ask FLex to send word forming letter list to the Webonary Cloud?

**Comment by phillip-hopper** [comment]
This is the alphabet from Webonary.

```
-,a,b,ɓ,c,ch,d,ɗ,e,ɛ,ɛ̃,f,g,gb,h,i,ĩ,ɩ,ɩ̃,j,k,kh,kp,l,m,n,ɲ,ŋ,ŋm,o,ɔ,ɔ̃,p,ph,r,s,t,th,u,ũ,ʋ,ʋ̃,v,w,,y,ƴ,z
```
The hyphen is clearly the first character. I'm not sure what the 4th character from the end is supposed to be. There isn't a font on my computer that has that code.

@hanatgit, does MongoDB support custom collations, or would this require creative regular expressions?

**Comment by peteroatley** [comment]
I tried searching the dictionary Verna linked to (but switching to .work) and searching for whole words doesn't produce any results. I tried baa and bana which have no accents. Searching for accented strings with "Match accents and tones" also produces no results when "match whole words" isn't checked e.g. bà.

**Comment by phillip-hopper** [comment]
It looks like it took care of the whole-word issue, but the initial attempt did not take into account diacritics
