### ISSUE TITLE
On Reversal Index Browse page, only 1 page on entries is being shown for each alphabet header

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#503]
Not all entries are not being returned on the Reversal Browse pages, https://www.webonary.org/daasanach/browse/browse-english/?lang=en? Each alphabet page on the Reversal Browse page only returns 1 page of entries.
Normally there are Page buttons:
![image](https://user-images.githubusercontent.com/53490028/216175692-b4aeb45c-c3c4-4377-bd6f-a4ba0b5db221.png)

The Page buttons are missing on this site,  https://www.webonary.org/daasanach/browse/browse-english.
![image](https://user-images.githubusercontent.com/53490028/216175477-2acd0e69-2df1-4f17-9893-01ea0cedcc9d.png)

Phil says only 25 entries are being returned per page, but there are many more entries than that.
Phil says it's because the Cloud says the reversal entry count is zero.
![image](https://user-images.githubusercontent.com/53490028/216175174-db8dc8cc-6fd1-4922-98a2-fd95ade76666.png)

**Comment by hanatgit** [comment]
The reversal entries for this dictionary use upper case letters for letter heads. But the dictionary itself uses lower case letters. While the search is done using case insensitivity, the count documents query is case sensitive. That is why the count is always 0, while the search itself yields resuts.

So we should be doing count documents in case insensitive search as well. 

NOTE: THIS MAY BE PROBLEMATIC IF THERE IS A LANGUAGE THAT USES MIXED LETTER HEADS. @vernastutzman is this possible?

**Comment by vernastutzman** [comment]
Unable to test. Need https://www.webonary.org/daasanach/?lang=en to be copied to .work.
