### ISSUE TITLE
How do Alphabetic Headers get set in Webonary for Reversals?

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#510]
How do Alphabetic Headers get set in Webonary for Reversals? I uploaded Babessi to https://www.webonary.org/test-stutzman4/browse/browse-english/ and there is a ch and a gh header showing. Neither of them has any entries.
There is no hint of ch or gh as being headers for the English reversal in FLEx. The vernacular however does have both a ch and a gh. Did the English Reversal alphabetic headers bleed over from the vernacular? They should NOT have been uploaded from FLEx.

View under the hood:
![image](https://user-images.githubusercontent.com/53490028/217664182-8647ec87-0d79-4888-aabb-b09b15f543d1.png)

View of the English Reversal Browse view:
![image](https://user-images.githubusercontent.com/53490028/217664367-1ff6e643-2fcd-430c-aea0-ed0d305e5926.png)

**Comment by hanatgit** [comment]
This appears to be a FLex issue, because these letters are being sent by FLex in the dictionary json.

**Comment by stevendyk** [comment]
FLEx team has added this to their current sprint.

**Comment by vernastutzman** [comment]
Determined to be a FLEx issue. The JIRA for the reversal issue is LT-21307. Should go into the sprint for 9.1.19.

**Comment by vernastutzman** [comment]
Looks fixed.
