### ISSUE TITLE
Placement of left margin is inconsistent

### ISSUE THREAD

**Issue by kwarfel** [sillsdev/webonary#518]
In scrolling through the Lama dictionary on Webonary.org, https://www.webonary.org/lama/?lang=en, I see that the left margin is sometimes further left/right on one page than it is on the next one. This seems strange. I expected the left margin to be consistent throughout the dictionary.

As an example, I was looking through the words that begin with 'h', and then went to those which begin with 'ɩ'.
On this page, https://www.webonary.org/lama/browse/browse-vernacular-english/?letter=h&key=las&lang=en, the margin is all the way to the left of the page.
On this page, https://www.webonary.org/lama/browse/browse-vernacular-english/?letter=%C9%A9&key=las&lang=en the margin is further to the right.

I expected all pages to have the same left margin as the first of those two (h).

**Comment by vernastutzman** [comment]
I validated that the left margin is consistent on a phone.
