### ISSUE TITLE
When clicking on Alphabetic Header on Search Page, sometimes it doesn't jump to the right letter

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#522]
On sites with a bilingual UI, when using the non-default language, the jump from any letter on the Alphabetic Header buttons on the Search page goes to the first page in the Browse view.

![image](https://user-images.githubusercontent.com/53490028/227317895-162b8b1c-8bae-4159-aa6b-901e03d59d73.png)

![image](https://user-images.githubusercontent.com/53490028/227318336-00d1e7c8-0ccf-4d1c-bc55-17022eaebfc7.png)

For example, on the Phuien site (https://www.webonary.org/phuien/?lang=en), clicking on m takes us to the m page when the French UI has been selected because French is the default language. When you change to the English UI
![image](https://user-images.githubusercontent.com/53490028/227318941-354e5391-20d5-4849-a0fc-2dd29c074cc6.png)
and click on the letter m, it takes you to the first page in the Browse view:

![image](https://user-images.githubusercontent.com/53490028/227319258-a7266f5c-14c6-40bd-9dd1-0ea573b32294.png)

**Comment by phillip-hopper** [comment]
The href is mal-formed:

`https://www.webonary.org/phuien/browse/browse-vernacular-english/?lang=en?letter=m&key=pug&lang=en`
