### ISSUE TITLE
Search for part of speech in senses

### ISSUE THREAD

**Issue by hanatgit** [sillsdev/webonary#530]
There is a checkbox in FLEx, **If all senses share the grammatical information, show it first**. By default it is unchecked, but when it is checked, the part of speech is within the span class of _sharegrammaticalinfo_ (https://files.slack.com/files-pri/T5903HSGP-F051EUCTB7H/screen_shot_2023-04-05_at_12.55.43_am.png). When left unchecked, the part of speech is embedded within the span class of _sense_ with a guid (https://files.slack.com/files-pri/T5903HSGP-F051XUJP0RJ/screen_shot_2023-04-05_at_12.56.18_am.png).

![image](https://user-images.githubusercontent.com/53490028/230402140-54b5f072-3259-4b94-bb84-d6e726776e22.png)

https://www.webonary.work/test-stutzman7/ has been uploaded with that checkbox unchecked and https://www.webonary.work/test-stutzman6/ has been uploaded with that checkbox checked.
The same database has been uploaded to both sites.

Webonary needs to handle both cases.

_Originally posted by @vernastutzman in https://github.com/sillsdev/webonary/issues/525#issuecomment-1499126122_

**Comment by stevendyk** [comment]
Re-opened, reviewed in 5/2/23 team meeting. When sorting on headwords, there is one item per entry, not one entry per sense. Ref test-stutzman7,

**Comment by stevendyk** [comment]
Replaced by [issue 543](https://github.com/sillsdev/webonary/issues/543)

**Comment by vernastutzman** [comment]
I have no idea how to test this at this point.
