### ISSUE TITLE
Rungus UI

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#532]
There is a request for a Rungus UI on this site, https://www.webonary.org/rungus/. from Christine Dreiheller. She has filled out the Excel spreadsheet with a column for Rungus.
[UI-translations_for_webonary (Malay2).xls](https://github.com/sillsdev/webonary/files/11323142/UI-translations_for_webonary.Malay2.xls)

**Comment by vernastutzman** [comment]
Here are a few items you missed. They are in the excel spreadsheet I sent, but I've copied them here for your convenience. The first column is English; the 2nd is Malay; and the third column is Rungus. If the last column has an MR, then both languages need the translation. If there is an M, only Malay needs attention. If there is an R, only Rungus needs attention.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/VERNAS~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/VERNAS~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink="#954F72">



Last   upload: | Kemas kini terakhir | Natagan dit addau dot: | R |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --




</body>

</html>
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/VERNAS~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/VERNAS~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink="#954F72">



Terms of   Service | Syarat Perkhidmatan | Hoturan di Piokunan Mamakai diti Kamus sid   webonary | M |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --




</body>

</html>
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/VERNAS~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/VERNAS~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink="#954F72">



Browse | Kamus | Kamus | MR |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --




</body>

</html>
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/VERNAS~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/VERNAS~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink="#954F72">



Semantic Domains | Domain Semantik (Bidang makna) | Umpug do pongoretan isuhut harati | MR |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --




</body>

</html>
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/VERNAS~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/VERNAS~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink="#954F72">



Match   whole words | Padan perkataan keseluruhan | Sambatang o pongoretan | M |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --




</body>

</html>
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/VERNAS~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/VERNAS~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink="#954F72">



Browse   Rungus -- English -- Malay | Mencari perkataan Rungus -- Inggeris -- B.   Melayu | Mogihim do pongoretan do Rungus -- Inggeris   -- Malazu | MR |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --




</body>

</html>

**Comment by phillip-hopper** [comment]
* "Last upload:" is not in the spreadsheet. The translation you gave is for "Last update:". I updated the localizations.
* The string "Terms of Service" is not in Webonary. It's probably on a page somewhere.
* The string "Browse" is not in Webonary. It's probably on a page somewhere.
* The string "Browse Rungus -- English -- Malay" is not in Webonary. It's probably on a page somewhere.

**Comment by phillip-hopper** [comment]
@vernastutzman  I updated the localization files, with the exceptions noted above.

**Comment by vernastutzman** [comment]
Semantic Domains in the Dropdown box is missing.
<html>
<body>


Semantic Domains | Domain Semantik (Bidang makna) | Umpug do pongoretan isuhut harati
-- | -- | --



</body>
</html>

I'm also waiting for the translation for Match accents and tones.

**Comment by stevendyk** [comment]
[Verna] "Match accents and tones":

Malay: Cari termasuk tanda aksen dan tanda nada (diakritik) 
Rungus: Mogihim, do nokosuvang it ongotanda (diakritik) do pongingvagat (aksen) om dolou (ton)

**Comment by vernastutzman** [comment]
Semantic Domains still appears in English in both Rungus and Malay. See above.
Malay = Domain Semantik (Bidang makna)
Rungus = Umpug do pongoretan isuhut harati

The languages of the Landing page should be changed for Malay (2nd column) and Rungus (3rd column)
![image](https://github.com/sillsdev/webonary/assets/53490028/5cec79d9-68b8-46b8-a14a-13443ede3771)

English = Inggeris = Inggeris
Malay = Melayu = Malazu
Rungus = Rungus = Rungus

**Comment by vernastutzman** [comment]
In the Rungus language, Malay is spelled Malazu, not Melayu.
