### ISSUE TITLE
Lubwisi site displays vernacular incorrectly

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#533]
I uploaded Lubwisi to its site, https://www.webonary.org/lubwisi/browse/browse-lubwisi-english/. It looks like this:
![image](https://user-images.githubusercontent.com/53490028/234305680-20048ac5-3ab5-420b-b28d-4827204a0097.png)

Then I uploaded the same project to my test site, https://www.webonary.org/test-stutzman2/browse/browse-vernacular/ and it looks right,
![image](https://user-images.githubusercontent.com/53490028/234305946-8dd86b7e-7d5e-48d3-add9-3ee2b83562b8.png)

The reversal looks correct.

**Comment by vernastutzman** [comment]
The FLEx project can be accessed here: https://drive.google.com/file/d/1Vcyr__dQViCwllJmSYvusiYtc-g5BhqM/view?usp=share_link.

**Comment by vernastutzman** [comment]
I discovered that there is a checkbox for Display subentries as main entries. If I unchecked it then the vernacular browse view displayed fine.
![image](https://user-images.githubusercontent.com/53490028/234338978-62c4546f-a5c6-4a79-b27d-ffea5c023dd8.png)
After I unchecked it the option went away.
What is the purpose of that checkbox?

**Comment by phillip-hopper** [comment]
I am removing it for cloud sites. I assume it was added for a reason and I don't want to break any old sites that need it.
