### ISSUE TITLE
Search requests from Rebecca Moore

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#546]
From Rebecca: Can search functions in Webonary please be re-updated so that we: 
1) have the option to search in either/both languages without the need to select one or the other; and 
2) have the option to pull up all instances within a part of speech category while keeping the search text blank?

Both of these used to be options but a recent update has changed them. If this can be fixed on the user end, please let me know what I should do to bring these functions back. Thank you!

Verna's comment. Under languages, I guess we need to keep all languages as the default. I didn't think anyone would search for both languages at the same time. I guess I was wrong. So we need to add back the choice of All languages.

For the second point, in this example, there is one instance of Adjectival Pronoun. We don't know what it is and we want to find it, but when we search for it, it says, "No matches..."
![image](https://github.com/sillsdev/webonary/assets/53490028/060b9313-5d0c-491c-b197-56ea47b3adc3)

**Comment by phillip-hopper** [comment]
@vernastutzman @hanatgit If I remember correctly, this is because it's not possible to search for a blank string in the cloud back end.

Also, what is the URL for the site in question?

**Comment by vernastutzman** [comment]
I did this Search on https://www.webonary.org/daasanach?s=&search=Search&key=dsh&pos=ADJ-PN&semantic_domain=&search_options_set=1&match_whole_words=1&lang=en.

**Comment by vernastutzman** [comment]
This is awesome!!!

On #546, it finds most of the Parts of Speech I search for, except the Adjective Singular (https://www.webonary.work/daasanach?s=&search=Search&key=dsh&pos=ADJ%28SG%29&semantic_domain=&search_options_set=1&match_whole_words=1&lang=en).
On https://www.webonary.work/test-stutzman?s=&search=Search&key=fr&pos=adv&semantic_domain=&search_options_set=1, it says there are 4 instances, but it finds 5.
