### ISSUE TITLE
Semantic Domain links should jump to the Semantic Domain Browse page

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#563]
In the Browse view (https://www.webonary.org/liko_dictionnaire_illustre/browse/browse-vernacular-french/?lang=en), when clicking on the Semantic Domain, currently no meaningful activity happens.
![image](https://github.com/sillsdev/webonary/assets/53490028/eb351acf-31cd-4307-abfd-07aa0bbb2c21)

Currently, it will provide this screen (https://www.webonary.org/liko_dictionnaire_illustre?s=&tax=Nourriture+d%E2%80%99origine+v%C3%A9g%C3%A9tale&lang=en), which is meaningless:
![image](https://github.com/sillsdev/webonary/assets/53490028/cea093dc-62e2-40c5-ab78-24b641360b0a)

The desired outcome of clicking on the Semantic Domain should be to take us to the Semantic Domain page (https://www.webonary.org/liko_dictionnaire_illustre/browse/categories/?semdomain=Food%20from%20plants&semnumber=5.2.3.1.&lang=en) with the focus on the Semantic Domain that was clicked, in this case 5.2.3.1.
![image](https://github.com/sillsdev/webonary/assets/53490028/058c416e-4564-48e7-9f16-8bf3dc46bcdf)

**Comment by phillip-hopper** [comment]
Link should look something like this:
```
/halbi/browse/categories/?semdomain=Table&semnumber=5.1.1.1.
```
