### ISSUE TITLE
When New Picture Author & Copyright information fields are uploaded, the separating punctuation is lost

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#585]
I uploaded the Sample database 7 to my test site:
https://www.webonary.org/test-stutzman5/browse/browse-vernacular/?key=fr&letter=l
This upload includes new fields never uploaded to Webonary before. The formatting is messed up in several places.
![image](https://github.com/sillsdev/webonary/assets/53490028/c328e484-843e-48de-baae-b91b35ae5e9d)

Here is how it looks in FLEx:
![image](https://github.com/sillsdev/webonary/assets/53490028/bc269ee5-a7b0-4195-abe3-616abd282576)

**Comment by phillip-hopper** [comment]
@vernastutzman it appears FLex added some new CSS classes that are not in the CSS files they send to us. That shouldn't be difficult work around. I'll see if I can find someone who has a list of the new CSS classes.
