### ISSUE TITLE
Add the Spanish equivalent for Semantic Domains

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#587]
The Spanish equivalent for Semantic Domains is Dominios semánticos. It is not showing up on the landing page.
![image](https://github.com/sillsdev/webonary/assets/53490028/0b2d569a-3096-43de-9c4e-a15171c9df51)

The dates on the https://www.webonary.org/tepehuano-sureste/ landing page look crazy :
![image](https://github.com/sillsdev/webonary/assets/53490028/66c4ccb5-909e-4ba0-9a67-41e5f07d3394)

**Comment by phillip-hopper** [comment]
I also added the Spanish and French localization files for WordPress, so the month and day names should translate now also.
