### ISSUE TITLE
Map display not showing new/all pins

### ISSUE THREAD

**Issue by peteroatley** [sillsdev/webonary#610]
The OpenStreetMap graphic on the front page is not showing all the dictionary locations which are registered in Wordpress. e.g. Nepal has 17 dictionaries registered but only 10 show on the map.

Yesterday I added South Efate for Vanuatu but the pin is not showing. 
![image](https://github.com/sillsdev/webonary/assets/144733976/34ade404-c9e5-4fd7-8680-64ebf0a643ad)
![image](https://github.com/sillsdev/webonary/assets/144733976/cb97090c-56ac-459f-aad6-2e008afaf941)

**Comment by phillip-hopper** [comment]
The permissions on the `webonary-sites.gpx` file were not correct. Should be working now.
