### ISSUE TITLE
Change to subscription form

### ISSUE THREAD

**Issue by peteroatley** [sillsdev/webonary#630]
We have changed our newsletter sender from Mailchimp to Sender.net. The embedded form on the sign-up page needs to be changed.

https://www.webonary.org/join-the-dictionary-lexicography-services-mailing-list/

Here are the instructions from Sender:
Integration instructions
Install the following snippet of Javascript on every page of your website right before the closing </head> tag.

You only need to add this snippet once, even if you plan to have a few different web forms.

```
<script>
  (function (s, e, n, d, er) {
    s['Sender'] = er;
    s[er] = s[er] || function () {
      (s[er].q = s[er].q || []).push(arguments)
    }, s[er].l = 1 * new Date();
    var a = e.createElement(n),
        m = e.getElementsByTagName(n)[0];
    a.async = 1;
    a.src = d;
    m.parentNode.insertBefore(a, m)
  })(window, document, 'script', 'https://cdn.sender.net/accounts_resources/universal.js', 'sender');
  sender('7e3a5289c58556')
</script>
```

After installing Javascript code, you need to install the following snippet of HTML code where you want to embed this form.

`<div style="text-align: left" class="sender-form-field" data-sender-form-id="lq25r3gie5djvdhjta5"></div>`

**Comment by phillip-hopper** [comment]
I only put the script on that one page, not every page like the instructions say to do.

**Comment by peteroatley** [comment]
New form is working
