### ISSUE TITLE
Parts of speech display problem

### ISSUE THREAD

**Issue by peteroatley** [sillsdev/webonary#651]
The Parts of Speech drop down list on the search page only shows all parts of speech if the FLEx "Category Info" field is used in the export of FLEx to Webonary. If the "Grammatical Info (Name or Abbrev)" field is used, the field only shows 1 entry each for Noun and Verb. 

![image](https://github.com/sillsdev/webonary/assets/144733976/65ad4666-2169-4a8d-bfa2-9d4ec4e51b03)

![image](https://github.com/sillsdev/webonary/assets/144733976/7aa1d6d9-c32c-434a-8d88-2c06259cc650)

Category Info only shows an abbreviation for the POS which means the full POS name, can't be used in the Webonary dictionary if the POS list is needed.

![image](https://github.com/sillsdev/webonary/assets/144733976/a420dfcc-dcc3-40c1-8ba0-7ed833b548c7)

![image](https://github.com/sillsdev/webonary/assets/144733976/2a19fbfc-d19e-4428-8e93-0de419ad088a)

Webonary should check which of the three fields "Gram Info (Name)", "Gram Info (Abbrev)", and/or "Category Info" is used and populate the drop down list accordingly.

![image](https://github.com/sillsdev/webonary/assets/144733976/3a802a5f-e2a6-4d08-b3e3-0cfe77501cf3)

**Comment by phillip-hopper** [comment]
@peteroatley the site appears to be working correctly now. Are you able to upload to .work the way that doesn't work, so I can do some debugging?

**Comment by peteroatley** [comment]
@phillip-hopper I tested it on Webonary.work and as you said if an abbreviation field is used the POS drop-down is populated correctly. If only the name field is used it doesn't populate. If you upload a name and an abbreviation field it populates but doesn't look nice since both are displayed.

Is it possible to create a POS index based on the name so that if gramname is used the drop-down can be populated?

**Comment by phillip-hopper** [comment]
@peteroatley I need some test data. Are you able to upload to a test site, without the abbreviation field, so I can experiment?

**Comment by peteroatley** [comment]
@phillip-hopper I have uploaded the Komo dictionary with the full POS name to https://www.webonary.work/test-oatley/

Thanks.

**Comment by phillip-hopper** [comment]
@peteroatley, is this still a problem? The Komo site appears to be working correctly now.

**Comment by peteroatley** [comment]
@phillip-hopper, I tested uploading a dictionary with different configurations for the part of speech. FLEx now looks like it is only uploading the abbreviation into one Mongodb field ("senses.morphosyntaxanalysis.partsofspeech.value") no matter what configuration you specify. So the part of speech drop down works but you can't display the full part of speech.

I'll close this and talk to Verna about what we do about displaying the full name.
