### ISSUE TITLE
Site name missing in email to user  for new site

### ISSUE THREAD

**Issue by peteroatley** [sillsdev/webonary#674]
When a new site is published, webonary@sil.org and possibly the site owner get an email confirming publication. Currently the email just says the site was published but doesn't give the name.

Is it possible to put the site name in the subject line and the body of the email?

![image](https://github.com/sillsdev/webonary/assets/144733976/90fb8d61-3475-434f-8083-4e8afb541527)

**Comment by phillip-hopper** [comment]
wp-resources/plugins/webonary-create-site/webonary-create-site.php

**Comment by peteroatley** [comment]
We tested this on webonary.work and didn't see a change in the email. The message says it has been published on webonary.org is this just static text in the email?



![Image](https://github.com/user-attachments/assets/181c2407-2b12-47ed-8ffe-2655072b4546)

**Comment by peteroatley** [comment]
This is now working.
