### ISSUE TITLE
Search Box - 'Match whole words' error message is confusing 

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#82]
Match whole words does not seem to be working.

This Message does not seem to be useful-too confusing for user:
Because of the brevity of your search term, partial search was omitted.
Click here to include searching through partial words.

SHOULD NOT BE DISPLAYED

**Comment by hanatgit** [comment]
Whole/partial search is working, except when there are multiple words (another issue). 

For this, just **remove the confusing message**

**Comment by vernastutzman** [comment]
Wait with this issue until #184, https://github.com/sillsdev/webonary/issues/184
 has been addressed.

**Comment by vernastutzman** [comment]
Possible wording for the error message is: "Only showing whole words that matched your string (if any).  To search for partial matches as well (possibly with a lot of results), click here."

**Comment by bbryson** [comment]
Just checking to see if this is still "In progress".  Is there an estimated ship date for it, so we can test for it?
