### ISSUE TITLE
Search Box - only finds first 2 levels of Semantic Domains

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#85]
Currently the Search only searches through the first two levels of the Semantic Domain labels. There is a possibility of 5 levels.
For example, if you search for person, it finds person (2.0). If you search for body, it finds body (2.1), but if you search for head (2.1.1.), it doesn't find it.

**Comment by hanatgit** [comment]
Not a bug. Insufficient test data. Verified that it does work correctly with Verna.
