### ISSUE TITLE
Vowels with diacritics displayed incorrectly

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#96]
Vowels with diacritics show as a question mark in a diamond. This may mean that the font is missing or that Unicode rendering is not happening correctly.
![Diacritics](https://user-images.githubusercontent.com/53490028/85876280-19ddc680-b79b-11ea-8193-9268175e6840.JPG)

**Comment by vernastutzman** [comment]
https://www.webonary.work/test-stutzman1/browse/browse-vernacular/?letter=w&key=bum

**Comment by bbryson** [comment]
This happens everywhere an entry is displayed.

Verna gave one example.  Here is another:

https://www.webonary.work/ut-hun/browse/browse-vernacular/?letter=a&key=dud

**Comment by hanatgit** [comment]
This might be an issue with FLex when it calls the cloud api. For example, see https://www.webonary.work/spanish-englishfooddictionary/browse/browse-vernacular/?key=es&lang=en. Diacritical markers are shown correctly. This data was uploaded not using FLex, but through the legacy import script using dictionary zip file.

**Comment by hanatgit** [comment]
Confirmed that the same characters known to give problems when uploaded from FLex are processed correctly by the legacy parser, which uses charset="utf-8" by default. See the result at https://www.webonary.work/spanish-englishfooddictionary/g497d2a94-b2d1-4c40-b4ff-768990c7ba2f/?lang=en

I am referring this issue to Jason
