### ISSUE TITLE
Search page does not list languages

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#97]
On the Search page, there is not a list of languages with the number of entries for each.
![Search](https://user-images.githubusercontent.com/53490028/85876790-d8015000-b79b-11ea-88c7-9cf8ec33c21f.JPG)

**Comment by bbryson** [comment]
This happens on the "landing page" for any project, which is also the page you get to by clicking on the Search tab.

https://www.webonary.work/ut-hun/
https://www.webonary.work/test-bryson/
https://www.webonary.work/test-stutzman1
