### ISSUE TITLE
Import Data Progress not working

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#99]
![ImportData](https://user-images.githubusercontent.com/53490028/85877763-44c91a00-b79d-11ea-98c6-6c24272c22ac.JPG)

Date of last import is not correct

**Comment by peteroatley** [comment]
Where was this screenshot taken? I can't find it on FLEx or Webonary.

**Comment by vernastutzman** [comment]
It appears to be a Webonary upload status, but it was taken more than 3 years ago, so it likely has changed.
https://www.webonary.org/test-stutzman1/wp-admin/admin.php?page=webonary @peteroatley

**Comment by peteroatley** [comment]
I checked on my test site and the time is one hour out so it doesn't seem to be applying the time zone correction.
![image](https://github.com/sillsdev/webonary/assets/144733976/37b7ed24-bf45-437d-a6de-9955f9c93558)

**Comment by vernastutzman** [comment]
No longer valid.

**Comment by stevendyk** [comment]
Closed - no longer relevant
